# Config for training the VAE on DEM

model:
  class_name: ddm.encoder_decoder.AutoencoderKL
  embed_dim: 8
  lossconfig:
    # perceptual_weight: 0.0  # Set this to zero to disable LPIPS
    disc_start: 50001
    kl_weight: 0.000001
    disc_weight: 0.5
    disc_in_channels: 1         # MATCH
  ddconfig:
    double_z: True
    z_channels: 8
    resolution: [ 64, 64 ]
    in_channels: 1              # MATCH
    out_ch: 1                   # MATCH
    ch: 128
    ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
    # E.g. if ch_mult = [1,2,4,8], then num_down = 3, so 256/2/2/2 = 32
    # ch_mult: determines the increase in channels for each downsampling layer.
    # E.g. if ch_mult = [1,2,4,4], then the number of channels will be 128 -> 256 -> 512 -> 512
    num_res_blocks: 2
    attn_resolutions: [ ]
    dropout: 0.0
  ckpt_path: #'/data/huang/pretrain_weights/ldm-ae/model-kl-d4.ckpt'

data:
  class_name: ddm.data.SatelliteDataset
  image_size: [64, 64]
  # data_dir: "/gws/nopw/j04/sensecdt/data/internal/majorTOM/world/Core-DEM"  # Path to your satellite data
  data_dir: "/tmp/majorTOM/world/Core-DEM"  # Path to your satellite data
  # data_dir: "/tmp/small_test/Core-DEM"  # Path to your satellite data
  tif_bands: ['DEM']     # Bands to use (R,G,B,NIR)
  satellite_type: "DEM"                     # Type of satellite data
  augment_horizontal_flip: True
  center_crop: False
  normalize_to_neg_one_to_one: True
  min_db: 0.000006 # np.log1p(0.000001)
  max_db: 9.088  # np.log1p(8849) # Everest height
  min_positive: 5.899129519093549e-06 # 
  batch_size: 16
  num_workers: 4

trainer:
  gradient_accumulate_every: 2
  lr: !!float 5e-6
  min_lr: !!float 1e-6
  train_num_steps: 500000
  save_and_sample_every: 10000
  log_freq: 1000
  resume_milestone: 'last' # Used for resuming from a checkpoint
  results_folder: './results/DEM_64x64_DEM_latent_8'
  amp: False
  fp16: False

# Enable wandb logging
wandb:
  enabled: True
  project: "satellite-vae"
  name: "DEM_64x64_DEM_latent_8"
  entity: "mespinosami"
  tags: ["DEM", "VAE"]
  log_images: True 